"""Swap corrected figures into exported body slides, in place of the figure Google Slides baked in.

Each entry maps a PDF page number to a replacement figure: an SVG from figures/out/ (generated by
figures/build.sh, rasterised here at the box width) or a PNG. The slide's figure rectangle comes from the PDF itself (the page's single image placement), so
the new figure lands exactly where the old one was, fitted inside that box and centred.

A page may also map to a LIST of figures: the page becomes one slide per figure, named s012a.png,
s012b.png, ... so they sort into the page's place (a build-up or a step sequence drawn in the figure
itself), and the original sNNN.png is removed. A page mapped to None is dropped. The slide lists
(prague-deck/slides.json, slides.js) are rewritten from the slides/ folder afterwards, since
make_slides.py wrote them before this ran. Run after make_slides.py, before makeover.py:

    python3 make_slides.py deck.pdf --skip 1
    python3 makeover/patch_figures.py deck.pdf
    python3 makeover/makeover.py
"""
import io
import json
import sys
from pathlib import Path
import fitz
from PIL import Image

HERE = Path(__file__).parent
DECK = HERE.parent / 'prague-deck'
OUT = HERE.parent / 'figures/out'                           # generated by figures/build.sh from the generators in figures/
CHAIN = [OUT / f'fig-ht-6{t}-chain.svg' for t in ('a1', 'a2', 'a', 'b', 'c', 'd', 'e')]
FIGURES = {12: CHAIN,                                        # the collision-chain sequence, 2026-10-01:
           13: None,                                         # 7.2 -> 8.0 -> (key, expiry into the object) -> 8.1;
                                                             # it covers what pages 12 and 13 showed, so 13 goes
           16: OUT / 'fig-fb-1-skiplist-topology.svg',       # explicit arrowheads (librsvg mis-orients <marker>)
           17: OUT / 'fig-fb-2-fbtree-topology.svg'}
TRIM = {16, 17}      # crop the figure's own whitespace margin before fitting, so it fills the box like the
                     # export did. NOT for the chain frames: their shared canvas is what keeps every
                     # object in place from one click to the next.


def figure_box(page, slide):
    imgs = page.get_images(full=True)
    assert len(imgs) == 1, f'page {page.number + 1}: expected one baked figure, found {len(imgs)}'
    rect = page.get_image_rects(imgs[0][0])[0]
    k = slide.width / page.rect.width
    return tuple(round(v * k) for v in (rect.x0, rect.y0, rect.x1, rect.y1))


MONO = 'DejaVu Sans Mono'                                    # cairosvg does not resolve a generic 'monospace'; pin the deck's label font


def load_figure(fig, bw):
    if fig.suffix.lower() == '.svg':                        # rasterise at the box width: crisp at native slide resolution
        import re
        import cairosvg
        svg = re.sub(r'font-family="[^"]*"', f'font-family="{MONO}"', fig.read_text())
        png = cairosvg.svg2png(bytestring=svg.encode(), output_width=bw)
        return Image.open(io.BytesIO(png)).convert('RGBA')
    return Image.open(fig).convert('RGBA')


def trimmed(im, pad=12):
    """Crop to the ink (anything darker than near-white), plus a small margin."""
    from PIL import ImageOps
    flat = Image.new('RGB', im.size, (255, 255, 255)); flat.paste(im, mask=im.split()[3])
    bbox = ImageOps.invert(flat.convert('L')).point(lambda v: 255 if v > 20 else 0).getbbox()
    if not bbox:
        return im
    return im.crop((max(0, bbox[0] - pad), max(0, bbox[1] - pad),
                    min(im.width, bbox[2] + pad), min(im.height, bbox[3] + pad)))


def patched(slide, box, fig, trim=False):
    bw, bh = box[2] - box[0], box[3] - box[1]
    new = load_figure(fig, bw * 2 if trim else bw)      # trimmed figures grow to fill the box: start oversize so the fit downscales
    if trim:
        new = trimmed(new)
    s = min(bw / new.width, bh / new.height)
    new = new.resize((round(new.width * s), round(new.height * s)), Image.LANCZOS)
    out = slide.copy()
    out.paste((255, 255, 255), box)                         # clear the old figure
    x = box[0] + (bw - new.width) // 2
    y = box[1] + (bh - new.height) // 2
    out.paste(new, (x, y), new)
    return out, s


pdf = fitz.open(sys.argv[1])
for page_no, fig in FIGURES.items():
    slide_path = DECK / f'slides/s{page_no:03d}.png'
    if fig is None:
        if slide_path.exists():
            slide_path.unlink()
        print(f's{page_no:03d}: dropped')
        continue
    page = pdf[page_no - 1]
    slide = Image.open(slide_path).convert('RGB')
    box = figure_box(page, slide)
    if isinstance(fig, list):
        for i, f in enumerate(fig):
            out, s = patched(slide, box, f)
            name = f's{page_no:03d}{chr(ord("a") + i)}.png'
            out.save(DECK / 'slides' / name)
            print(f'{name[:-4]}: {f.name} -> box {box}, scaled x{s:.2f}')
        slide_path.unlink()
    else:
        out, s = patched(slide, box, fig, trim=page_no in TRIM)
        out.save(slide_path)
        print(f's{page_no:03d}: {fig.name} -> box {box}, scaled x{s:.2f}')

names = [f'slides/{p.name}' for p in sorted((DECK / 'slides').glob('s*.png'))]
(DECK / 'slides.json').write_text(json.dumps(names, indent=1))
(DECK / 'slides.js').write_text('window.SLIDES = ' + json.dumps(names) + ';\n')
print(f'{len(names)} slides -> {DECK / "slides.json"}')
